=== esaude/esaude-emr-poc/poc_config/openmrs/apps/clinicalServicesSchema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "Clinical service",
  "type": "object",
  "required": [
    "id",
    "formId",
    "label",
    "url"
  ],
  "properties": {
    "id": {
      "description": "The clinical service unique identifier.",
      "type": "string"
    },
    "formId": {
      "description": "The form uuid for the clinical service.",
      "type": "string"
    },
    "label": {
      "description": "The translation key for the clinical service label.",
      "type": "string"
    },
    "url": {
      "description": "The URL path where the form will be displayed.",
      "type": "string"
    },
    "minOccur": {
      "description": "Minimum number of times this form can be filled.",
      "type": "string"
    },
    "maxOccur": {
      "description": "Maximum number of times this form can be filled.",
      "type": "string"
    },
    "constraints": {
      "description": "Constraints that determine whether the form will be displayed in the clinical services list.",
      "type": "object",
      "properties": {
        "minAge": {
          "description": "The minimum required age for the patient.",
          "type": "string"
        },
        "maxAge": {
          "description": "The maximum required age for the patient.",
          "type": "string"
        }
      }
    },
    "actionConstraints": {
      "description": "Constraints that determine whether the add, edit and delete buttons are displayed.",
      "type": "object",
      "properties": {
        "requireCheckIn": {
          "description": "If the patient needs to be checked-in.",
          "type": "boolean"
        }
      }
    },
    "privilege": {
      "description": "Privilege required for the user to be able to fill the form.",
      "type": "string"
    },
    "markedOn": {
      "description": "TODO: don't know what this is for.",
      "type": "string"
    }
  }
}

=== esaude/esaude-emr-poc/poc_config/openmrs/apps/clinical/clinicalServices.json
[
    {
        "id": "003",
        "formId": "e28aa7aa-1d5f-11e0-b929-000c29ad1d07",
        "label": "VITAIS - ADULTO",
        "url": "/vitals/adult",
        "minOccur": "0",
        "maxOccur": "-1",
        "constraints": {
            "minAge": "15"
        },
        "markedOn": "283e551d-a470-4280-84fd-8f409f3caf7a"
    },
    {
        "id": "004",
        "formId": "e28ac028-1d5f-11e0-b929-000c29ad1d07",
        "label": "VITAIS - PEDIATRIA",
        "url": "/vitals/child",
        "minOccur": "0",
        "maxOccur": "-1",
        "constraints": {
            "maxAge": "14"
        },
        "markedOn": "283e551d-a470-4280-84fd-8f409f3caf7a"
    },
    {
        "id": "006",
        "formId": "e28aa7aa-1d5f-11e0-b929-000c29ad1d07",
        "label": "OMS ESTADIO - ADULTO",
        "url": "/oms/adult",
        "minOccur": "0",
        "maxOccur": "-1",
        "constraints": {
            "minAge": "15",
            "requireChekin": true
        },
        "markedOn": "2afd6fda-3003-4a68-bfa2-9a4e2ab2773d"
    },
    {

        "id": "007",
        "formId": "65896366-17b2-4c3e-9cce-440edcfe7b4e",
        "label": "ASPECTOS RELEVANTES",
        "url": "/story",
        "minOccur": "0",
        "maxOccur": "-1",
        "constraints": {
            "requireChekin": true
        }
    },
    {
        "id": "008",
        "formId": "e28aa7aa-1d5f-11e0-b929-000c29ad1d07",
        "label": "ANAMNESE E EXAME FÍSICO - ADULTO",
        "url": "/anamnese/adult",
        "minOccur": "0",
        "maxOccur": "-1",
        "constraints": {
            "minAge": "15",
            "requireChekin": true
        },
        "markedOn": "3ae77ecc-865b-4354-abf9-901f36715c70"
    },
     {
        "id": "010",
        "formId": "e28ac028-1d5f-11e0-b929-000c29ad1d07",
        "label": "ANAMNESE E EXAME FÍSICO - PEDIATRIA",
        "url": "/anamnese/child",
        "minOccur": "0",
        "maxOccur": "-1",
        "constraints": {
            "maxAge": "14",
            "requireChekin": true
        },
        "markedOn": "3ae77ecc-865b-4354-abf9-901f36715c70"
    },
    {
        "id": "009",
        "formId": "e28aa7aa-1d5f-11e0-b929-000c29ad1d07",
        "label": "DIAGNOSTICO - ADULTO",
        "url": "/diagnostics/adult",
        "minOccur": "0",
        "maxOccur": "-1",
        "constraints": {
            "minAge": "15",
            "requireChekin": true
        },
        "markedOn": "4bea5235-1ef3-45a3-a7de-c33850c74422"
    },
    {
        "id": "011",
        "formId": "e28ac028-1d5f-11e0-b929-000c29ad1d07",
        "label": "DIAGNOSTICO - PEDIATRIA",
        "url": "/diagnostics/child",
        "minOccur": "0",
        "maxOccur": "-1",
        "constraints": {
            "maxAge": "14",
            "requireChekin": true
        },
        "markedOn": "4bea5235-1ef3-45a3-a7de-c33850c74422"
    }

]

=== esaude/esaude-emr-poc/poc_config/openmrs/apps/social/clinicalServices.json
[
    {
        "id": "001",
        "formId": "e28b6096-1d5f-11e0-b929-000c29ad1d07",
        "label": "INFO SOCIAL - ADULTO",
        "url": "/anamnesis/a/adult",
        "minOccur": "1",
        "maxOccur": "-1",
        "constraints": {
            "minAge": "15",
            "requireChekin": false
        }
    },
    {
        "id": "002",
        "formId": "e28b6b0e-1d5f-11e0-b929-000c29ad1d07",
        "label": "INFO SOCIAL - PEDIATRIA",
        "url": "/anamnesis/a/child",
        "minOccur": "1",
        "maxOccur": "1",
        "constraints": {
            "maxAge": "14",
            "requireChekin": false
        }
    }
]

=== esaude/esaude-emr-poc/poc_config/openmrs/apps/clinic/clinicalServices.json
[
  {
    "id": "003",
    "formId": "e28aa7aa-1d5f-11e0-b929-000c29ad1d07",
    "label": "COMMON_VITALS_FORM",
    "url": "/vitals/adult",
    "minOccur": "0",
    "maxOccur": "-1",
    "constraints": {
      "minAge": "15"
    },
    "actionConstraints": {
      "requireCheckIn": false
    },
    "markedOn": "283e551d-a470-4280-84fd-8f409f3caf7a",
    "privilege": "Vitals"
  },
  {
    "id": "004",
    "formId": "e28ac028-1d5f-11e0-b929-000c29ad1d07",
    "label": "COMMON_VITALS_FORM",
    "url": "/vitals/child",
    "minOccur": "0",
    "maxOccur": "-1",
    "constraints": {
      "maxAge": "14"
    },
    "actionConstraints": {
      "requireCheckIn": false
    },
    "markedOn": "283e551d-a470-4280-84fd-8f409f3caf7a",
    "privilege": "Vitals"
  },
  {
    "id": "006",
    "formId": "e28aa7aa-1d5f-11e0-b929-000c29ad1d07",
    "label": "COMMON_WHO_FORM",
    "url": "/oms/adult",
    "minOccur": "0",
    "maxOccur": "-1",
    "constraints": {
      "minAge": "15"
    },
    "actionConstraints": {
      "requireCheckIn": true
    },
    "markedOn": "2afd6fda-3003-4a68-bfa2-9a4e2ab2773d",
    "privilege": "OMS Stadium"
  },
  {
    "id": "012",
    "formId": "e28ac028-1d5f-11e0-b929-000c29ad1d07",
    "label": "COMMON_WHO_FORM",
    "url": "/oms/child",
    "minOccur": "0",
    "maxOccur": "-1",
    "constraints": {
      "maxAge": "14"
    },
    "actionConstraints": {
      "requireCheckIn": true
    },
    "markedOn": "2afd6fda-3003-4a68-bfa2-9a4e2ab2773d",
    "privilege": "OMS Stadium"
  },
  {
    "id": "007",
    "formId": "65896366-17b2-4c3e-9cce-440edcfe7b4e",
    "label": "COMMON_RELEVANT_NOTES_FORM",
    "url": "/story",
    "minOccur": "0",
    "maxOccur": "-1",
    "constraints": {
    },
    "actionConstraints": {
      "requireCheckIn": true
    },
    "privilege": "Relevant Aspects"
  },
  {
    "id": "008",
    "formId": "e28aa7aa-1d5f-11e0-b929-000c29ad1d07",
    "label": "COMMON_ANAMNESE_BODY_EXAM_FORM",
    "url": "/anamnese/adult",
    "minOccur": "0",
    "maxOccur": "-1",
    "constraints": {
      "minAge": "15"
    },
    "actionConstraints": {
      "requireCheckIn": true
    },
    "markedOn": "3ae77ecc-865b-4354-abf9-901f36715c70",
    "privilege": "Anamnesis"
  },
  {
    "id": "010",
    "formId": "e28ac028-1d5f-11e0-b929-000c29ad1d07",
    "label": "COMMON_ANAMNESE_BODY_EXAM_FORM",
    "url": "/anamnese/child",
    "minOccur": "0",
    "maxOccur": "-1",
    "constraints": {
      "maxAge": "14"
    },
    "actionConstraints": {
      "requireCheckIn": true
    },
    "markedOn": "3ae77ecc-865b-4354-abf9-901f36715c70",
    "privilege": "Anamnesis"
  },
  {
    "id": "009",
    "formId": "e28aa7aa-1d5f-11e0-b929-000c29ad1d07",
    "label": "COMMON_DIAGNOSIS_FORM",
    "url": "/diagnostics/adult",
    "minOccur": "0",
    "maxOccur": "-1",
    "constraints": {
      "minAge": "15"
    },
    "actionConstraints": {
      "requireCheckIn": true
    },
    "markedOn": "4bea5235-1ef3-45a3-a7de-c33850c74422",
    "privilege": "Diagnosis"
  },
  {
    "id": "011",
    "formId": "e28ac028-1d5f-11e0-b929-000c29ad1d07",
    "label": "COMMON_DIAGNOSIS_FORM",
    "url": "/diagnostics/child",
    "minOccur": "0",
    "maxOccur": "-1",
    "constraints": {
      "maxAge": "14"
    },
    "actionConstraints": {
      "requireCheckIn": true
    },
    "markedOn": "4bea5235-1ef3-45a3-a7de-c33850c74422",
    "privilege": "Diagnosis"
  }
]
